services:
  postgres:
    image: postgres:16
    container_name: fast_food_db
    ports:
      - "9000:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fast_food
  redis:
    container_name: fast_food-redis
    image: redis:7.2.4
    ports:
      - "6379:6379"

