server:
  port: 8080
spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:1234/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
